name: free_malware_detection
description: "Flutter malware detection library for Android. Protect your app against potential threats with Talsec."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  android_intent_plus: ^5.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freerasp:
    path: ../../RASP/FreeRASP-Flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
